import React from 'react';
import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import { getPublishedPage } from '@/lib/content';
import { renderMarkdown, excerptFromMarkdown } from '@/lib/markdown';

/**
 * Rendering strategy: ISR.
 *
 * Editable marketing copy that changes rarely and is read constantly, so it is
 * cached and regenerated hourly. Saving in the admin calls revalidatePath, so
 * an edit is live immediately rather than up to an hour later.
 *
 * This route is the catch-all for CMS pages. Next.js matches its own static
 * routes first, which is why `RESERVED_SLUGS` refuses the slugs that would
 * otherwise be shadowed here and never appear.
 */
export const revalidate = 3600;
export const dynamicParams = true;

/**
 * Nothing is prerendered at build: an empty params list plus dynamicParams
 * means each URL is generated on its first request and cached from there.
 * Without this the build would need a reachable database, which couples every
 * deploy to the database being up.
 */
export async function generateStaticParams() {
  return [];
}

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const page = await getPublishedPage(slug);
  if (!page) return { title: 'Not found — My Lucky Dates' };

  const description = page.metaDescription || excerptFromMarkdown(page.bodyMarkdown);
  return {
    title: page.metaTitle || `${page.title} — My Lucky Dates`,
    description,
    alternates: { canonical: `/${page.slug}` },
    openGraph: {
      title: page.metaTitle || page.title,
      description,
      url: `/${page.slug}`,
      type: 'article',
    },
  };
}

export default async function CmsPage({ params }: PageProps) {
  const { slug } = await params;
  const page = await getPublishedPage(slug);
  if (!page) notFound();

  return (
    <>
      <Header />
      <main className="min-h-screen bg-background pt-32 pb-24">
        <article className="max-w-2xl mx-auto px-6 md:px-12">
          <h1
            className="font-sans font-extrabold text-foreground mb-8"
            style={{
              fontSize: 'clamp(2rem, 5vw, 3rem)',
              letterSpacing: '-0.03em',
              lineHeight: 1.05,
            }}
          >
            {page.title}
          </h1>

          {/*
            The markdown renderer escapes raw HTML and drops unsafe link
            schemes, so what reaches here is generated by us from the author's
            text rather than passed through from it.
          */}
          <div
            className="prose prose-stone max-w-none prose-headings:font-sans prose-headings:font-bold prose-a:text-primary"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(page.bodyMarkdown) }}
          />
        </article>
      </main>
      <Footer />
    </>
  );
}
