import React from 'react';
import type { Metadata } from 'next';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import Header from '@/components/Header';
import Footer from '@/components/Footer';
import Icon from '@/components/ui/AppIcon';
import { formatPublished } from '@/components/PostCard';
import { getPublishedPost } from '@/lib/content';
import { renderMarkdown, excerptFromMarkdown } from '@/lib/markdown';

/** Rendering strategy: ISR — see /[slug]. */
export const revalidate = 3600;
export const dynamicParams = true;

/**
 * Nothing is prerendered at build: an empty params list plus dynamicParams
 * means each URL is generated on its first request and cached from there.
 * Without this the build would need a reachable database, which couples every
 * deploy to the database being up.
 */
export async function generateStaticParams() {
  return [];
}

interface PageProps {
  params: Promise<{ slug: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { slug } = await params;
  const post = await getPublishedPost(slug);
  if (!post) return { title: 'Not found — BirthNote' };

  const description =
    post.metaDescription || post.excerpt || excerptFromMarkdown(post.bodyMarkdown);

  return {
    title: post.metaTitle || `${post.title} — BirthNote`,
    description,
    alternates: { canonical: `/blog/${post.slug}` },
    openGraph: {
      title: post.metaTitle || post.title,
      description,
      url: `/blog/${post.slug}`,
      type: 'article',
      publishedTime: post.publishedAt ?? undefined,
      images: post.coverImageUrl ? [post.coverImageUrl] : undefined,
    },
  };
}

export default async function BlogPostPage({ params }: PageProps) {
  const { slug } = await params;
  const post = await getPublishedPost(slug);
  if (!post) notFound();

  return (
    <>
      <Header />
      <main className="min-h-screen bg-background pt-32 pb-24">
        <article className="max-w-2xl mx-auto px-6 md:px-12">
          <Link
            href="/blog"
            className="inline-flex items-center gap-1.5 text-xs font-semibold text-muted-foreground hover:text-foreground transition-colors mb-8"
          >
            <Icon name="ArrowLeftIcon" size={12} />
            The Blog
          </Link>

          <div className="flex flex-wrap items-center gap-3 mb-4">
            {post.categoryName && post.categorySlug && (
              <Link
                href={`/blog/category/${post.categorySlug}`}
                className="px-3 py-1 rounded-full bg-accent/15 border border-accent/25 text-xs font-semibold text-accent-foreground"
              >
                {post.categoryName}
              </Link>
            )}
            {post.publishedAt && (
              <time dateTime={post.publishedAt} className="text-xs text-muted-foreground">
                {formatPublished(post.publishedAt)}
              </time>
            )}
          </div>

          <h1
            className="font-sans font-extrabold text-foreground mb-6"
            style={{
              fontSize: 'clamp(1.9rem, 5vw, 2.8rem)',
              letterSpacing: '-0.03em',
              lineHeight: 1.08,
            }}
          >
            {post.title}
          </h1>

          {post.excerpt && (
            <p className="font-serif italic text-lg text-muted-foreground mb-10 leading-relaxed">
              {post.excerpt}
            </p>
          )}

          {/* See /[slug]: the HTML here is generated by our renderer, not the author's. */}
          <div
            className="prose prose-stone max-w-none prose-headings:font-sans prose-headings:font-bold prose-a:text-primary"
            dangerouslySetInnerHTML={{ __html: renderMarkdown(post.bodyMarkdown) }}
          />

          <div className="mt-14 pt-8 border-t border-border">
            <Link
              href="/request-a-banknote"
              className="inline-flex items-center gap-2 px-5 py-2.5 bg-primary text-primary-foreground rounded-full text-sm font-semibold hover:bg-primary/90 transition-colors"
            >
              Find a note from your date
              <Icon name="ArrowRightIcon" size={14} />
            </Link>
          </div>
        </article>
      </main>
      <Footer />
    </>
  );
}
