import type React from 'react';

/**
 * Explicit registry of the icons this app actually uses.
 *
 * AppIcon resolves icons by name at runtime, which previously meant
 * `import * as HeroIcons` — a namespace import bundlers cannot tree-shake, so
 * every client bundle carried the entire Heroicons set. Naming the icons here
 * keeps the same string-based API while shipping only what is referenced.
 *
 * Adding a new icon to a page? Add its name to this list too, otherwise
 * AppIcon renders the question-mark fallback.
 */
import {
  ArchiveBoxIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowDownTrayIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  AdjustmentsHorizontalIcon,
  BanknotesIcon,
  Bars3Icon,
  CalendarDaysIcon,
  ChartBarIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  GiftIcon,
  HomeIcon,
  InformationCircleIcon,
  KeyIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  QuestionMarkCircleIcon,
  ShareIcon,
  ShieldCheckIcon,
  SparklesIcon,
  StarIcon,
  TrashIcon,
  TruckIcon,
  UserCircleIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';
import {
  ArchiveBoxIcon as SolidArchiveBoxIcon,
  ArrowLeftIcon as SolidArrowLeftIcon,
  ArrowPathIcon as SolidArrowPathIcon,
  ArrowRightIcon as SolidArrowRightIcon,
  ArrowRightOnRectangleIcon as SolidArrowRightOnRectangleIcon,
  ArrowDownTrayIcon as SolidArrowDownTrayIcon,
  ArrowUpIcon as SolidArrowUpIcon,
  ArrowDownIcon as SolidArrowDownIcon,
  AdjustmentsHorizontalIcon as SolidAdjustmentsHorizontalIcon,
  BanknotesIcon as SolidBanknotesIcon,
  Bars3Icon as SolidBars3Icon,
  CalendarDaysIcon as SolidCalendarDaysIcon,
  ChartBarIcon as SolidChartBarIcon,
  CheckBadgeIcon as SolidCheckBadgeIcon,
  CheckCircleIcon as SolidCheckCircleIcon,
  CheckIcon as SolidCheckIcon,
  ClockIcon as SolidClockIcon,
  Cog6ToothIcon as SolidCog6ToothIcon,
  CreditCardIcon as SolidCreditCardIcon,
  DocumentTextIcon as SolidDocumentTextIcon,
  EnvelopeIcon as SolidEnvelopeIcon,
  EnvelopeOpenIcon as SolidEnvelopeOpenIcon,
  ExclamationTriangleIcon as SolidExclamationTriangleIcon,
  GiftIcon as SolidGiftIcon,
  HomeIcon as SolidHomeIcon,
  InformationCircleIcon as SolidInformationCircleIcon,
  KeyIcon as SolidKeyIcon,
  LockClosedIcon as SolidLockClosedIcon,
  MagnifyingGlassIcon as SolidMagnifyingGlassIcon,
  QuestionMarkCircleIcon as SolidQuestionMarkCircleIcon,
  ShareIcon as SolidShareIcon,
  ShieldCheckIcon as SolidShieldCheckIcon,
  SparklesIcon as SolidSparklesIcon,
  StarIcon as SolidStarIcon,
  TrashIcon as SolidTrashIcon,
  TruckIcon as SolidTruckIcon,
  UserCircleIcon as SolidUserCircleIcon,
  XCircleIcon as SolidXCircleIcon,
  XMarkIcon as SolidXMarkIcon,
} from '@heroicons/react/24/solid';

export type IconComponent = React.ComponentType<React.SVGProps<SVGSVGElement>>;

export const outlineIcons: Record<string, IconComponent> = {
  ArchiveBoxIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowRightOnRectangleIcon,
  ArrowDownTrayIcon,
  ArrowUpIcon,
  ArrowDownIcon,
  AdjustmentsHorizontalIcon,
  BanknotesIcon,
  Bars3Icon,
  CalendarDaysIcon,
  ChartBarIcon,
  CheckBadgeIcon,
  CheckCircleIcon,
  CheckIcon,
  ClockIcon,
  Cog6ToothIcon,
  CreditCardIcon,
  DocumentTextIcon,
  EnvelopeIcon,
  EnvelopeOpenIcon,
  ExclamationTriangleIcon,
  GiftIcon,
  HomeIcon,
  InformationCircleIcon,
  KeyIcon,
  LockClosedIcon,
  MagnifyingGlassIcon,
  QuestionMarkCircleIcon,
  ShareIcon,
  ShieldCheckIcon,
  SparklesIcon,
  StarIcon,
  TrashIcon,
  TruckIcon,
  UserCircleIcon,
  XCircleIcon,
  XMarkIcon,
};

export const solidIcons: Record<string, IconComponent> = {
  ArchiveBoxIcon: SolidArchiveBoxIcon,
  ArrowLeftIcon: SolidArrowLeftIcon,
  ArrowPathIcon: SolidArrowPathIcon,
  ArrowRightIcon: SolidArrowRightIcon,
  ArrowDownTrayIcon: SolidArrowDownTrayIcon,
  ArrowRightOnRectangleIcon: SolidArrowRightOnRectangleIcon,
  ArrowUpIcon: SolidArrowUpIcon,
  ArrowDownIcon: SolidArrowDownIcon,
  AdjustmentsHorizontalIcon: SolidAdjustmentsHorizontalIcon,
  BanknotesIcon: SolidBanknotesIcon,
  Bars3Icon: SolidBars3Icon,
  CalendarDaysIcon: SolidCalendarDaysIcon,
  ChartBarIcon: SolidChartBarIcon,
  CheckBadgeIcon: SolidCheckBadgeIcon,
  CheckCircleIcon: SolidCheckCircleIcon,
  CheckIcon: SolidCheckIcon,
  ClockIcon: SolidClockIcon,
  Cog6ToothIcon: SolidCog6ToothIcon,
  CreditCardIcon: SolidCreditCardIcon,
  DocumentTextIcon: SolidDocumentTextIcon,
  EnvelopeIcon: SolidEnvelopeIcon,
  EnvelopeOpenIcon: SolidEnvelopeOpenIcon,
  ExclamationTriangleIcon: SolidExclamationTriangleIcon,
  GiftIcon: SolidGiftIcon,
  HomeIcon: SolidHomeIcon,
  InformationCircleIcon: SolidInformationCircleIcon,
  KeyIcon: SolidKeyIcon,
  LockClosedIcon: SolidLockClosedIcon,
  MagnifyingGlassIcon: SolidMagnifyingGlassIcon,
  QuestionMarkCircleIcon: SolidQuestionMarkCircleIcon,
  ShareIcon: SolidShareIcon,
  ShieldCheckIcon: SolidShieldCheckIcon,
  SparklesIcon: SolidSparklesIcon,
  StarIcon: SolidStarIcon,
  TrashIcon: SolidTrashIcon,
  TruckIcon: SolidTruckIcon,
  UserCircleIcon: SolidUserCircleIcon,
  XCircleIcon: SolidXCircleIcon,
  XMarkIcon: SolidXMarkIcon,
};
